@HOST = http://localhost:3000

### register post
POST {{HOST}}/api/user/register HTTP/1.1
Content-Type: application/json

{
  "username" : "Admin",
  "password" : "123456",
  "password2" : "123456"
}

### login post
POST {{HOST}}/api/user/login HTTP/1.1
Content-Type: application/json

{
  "username" : "abc",
  "password" : "123456"
}

### current get
GET {{HOST}}/api/user/current HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwN2RlMjI1MzNlZTA0MjBjYzVkZTIxYyIsInVzZXJuYW1lIjoiQWRtaW4iLCJpYXQiOjE2MTg5NTU4ODksImV4cCI6MTYxODk1OTQ4OX0.RGwO-xb964ifofmJGiuB4m1Iyp9PWyq4tDSatjJoiys

### current POST