@HOST = http://localhost:3000

### test
GET {{HOST}}/api/user/test HTTP/1.1

### register post
POST {{HOST}}/api/user/register HTTP/1.1
Content-Type: application/json

{
  "username" : "Admin",
  "password" : "123456"
}

### login post
POST {{HOST}}/api/user/login HTTP/1.1
Content-Type: application/json

{
  "username" : "Admin",
  "password" : "123456"
}